[project]
site_name = "Autolume - Documentation"
site_url = "https://metacreation-lab.github.io/autolume"
repo_name = "Metacreation-Lab/autolume"
repo_url = "https://github.com/Metacreation-Lab/autolume"
extra_css = ["assets/extra.css"]
nav = [
    "index.md",
    "prepare.md",
    { Train = ["train/index.md", "train/training-aug.md"] },
    "perform.md",
    "tools.md",
    "feedback.md",
]

[project.theme]
variant = "classic"
favicon = "assets/logo.webp"
logo = "assets/logo.webp"
features = ["navigation.footer", "navigation.indexes"]

[project.theme.palette]
primary = "custom"
accent = "custom"

[project.extra.version]
provider = "mike"
default = "latest"
